sudo: required
dist: trusty
language: node_js
node_js:
#- stable
- "9"
branches:
  except:
  - gh-pages
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- yarn add polymer-cli
- polymer install --variants
script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --plugin sauce --skip-plugin
  local; fi
after_success:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$DEPLOYSECRET"
  -in deploy.enc -out deploy_key -d; fi
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- "./ghp.sh"
env:
  global:
  - secure: MDep/89XEQYQNv/pJ8B5S3CQubPGM+WA/Lat4vnwveMyfNICGbVG2LJSjQ+9KpyXHQuGUx3WTWX2FiccoXadhD7/YgIYX6cbi6BfhqT5PV4KL7isIvKk/HLfwC3HJuT4aIazuC3x49zNd5ad/y0CRqNanCJ6d3TRuUnkV26V0fUQD3NsSvoOLKinknjbmxvhOHkHeiFIUpnkcktEQGdn8rsueGI5424u1UYdXSQxtKNfwpaAhia/H8Q8mRU+FJ8T9MexXv563grkbsDwecI1k50esR4QArSqvn9EY9EjPPDTaQ0O7MvavoG6jGvqtmx0FJTiIIZQh2MTzZ6AurpHCoLnKWQx34vrTeO5Tm/AwzIuGQlNEtH+4lffFSrWkSlRuVuNA5BVWmyRTc5wvyhfFLd3aH52C0LwwCGxPw9f16eEuZ2YsqGCoqT8lYVSRYF3xOsdYjyRViNpieZwDob06ZCVFVT6b6QdCw0u3u4+z7+qmYvgGMROsHn0X1O+7ZwRjb255qcUXg5ulMLPMjyA/VOm73nCyoCqm26l8NR4H3O4bqRPaDJOqMfU4NnJJZ8iNRNLMIfXbRX1e+Fx6e/A0WD36Jkh6o1r7icKcu/nUJgQodIXPL3ojXCcUFeY6gB8emzunnTfXDYNjSgECp2nCtYHhfbn9Mk2qkPN/ILPFP4=
  - secure: ujmqigvTa/NKYi0IOCGWxnJwOZYdkUjhYQzpKRwZZ/HlwqkjR0oHaZUjBCLZlnoMbZQBLyGIos3tMhmvPLKluCl4yPnUAWxNeTat+zpWUiWyyu4nghwHXzpBv5lUr6czbxibbwSenKgfvup9e1ULkjgbuvOfe0Rjict9fxNK2yK/IA2G6hAdjHS66BQrRG05N4eL3W53yXzqQZYS4I4N8SrU4PwWjZFazoMOi4liWUhRXpu+FPKL0BKO3vWdq0z7wIvKhoeMof104WQIZJE3+lLcTCztmv6Sv78HEQeLKHKWa6Yhigc0xBhVh8gHTOUTRyAG8VJuKozf5aQ58pGBHjXcdlGo1J3me01MUjCFhEcrIiiv/4jaCqCo3RMatmMkHAgG71IvWThC10BBrNED9ogHLOXeZLNOVY8c6d0j+FSabpg2/FN5b22ttVXkPgyGYCS08UYrVL2NIAKvuWvh7YQadHT4DpuNpdSRrg6hm6uMw1zwBXkNmFNpWOnVYcfp7FpdKMyx8HYF8tBxRSyK30SoxlvNynvFhpLgQU9JscWVA0hkoECvHhdrol8yHGiULLKkR1VYF1qMk5T/Y5tWMPhHPZuSOnsMxDAhQQS2zUqvNumAJHCxREp8yvRgZq5ht5JF2WIIQM7sdRY8LxuyEyoqKa6OLqrfv70fCKvolVg=
  - secure: Gr0til22d6adhaY+XyTBdc4ipC989p96SsanlE8yyFknNYrMqVlorQ7iBFHuQcWQ9C54v5v3FVvwGrX97G+g0mEz4THNH55Z57FxOovqEud79sVeWOhV5vQmMYGFuiuPAW3sZTLYsKtSW1xA/4K+T7JjCXMVsVcKU0QSVUF7vzngORpRnat5PWl/LLDGAh/KsdQwdDItAkdcq1y9hTuo6dQaXlHhYCilCXjvgjwnluIiIHjbwdle831OxcuWDi4Tqt/zgibYbexPPDoDx/96wPjM/tkestgfG9TCJKifE07bDDgmfqgarLs7xmYICI+Dcx4KNvfd/YSWnILV2iPQHoigeLYV0LkWgOjtqebOtmAp5I+WXgChfDgUut8g3Zi505bK1LAX+c3s+qIaipl9KDKhUKa944YxRj67Uo8hWvsxCb18KK95mfCsTKCa3IqfBUaitgTgtSdCCo8Hbpc1yLTdzReLE/rcplg1HmuKagJhtPLmLG+ey3DATqhZ27IielAXdG5lDiPsaLYnFRm4vgWnIi/AEix20ccb8c3LKin353aJsemcJrVIj1SB5PMMp24YicLUDgDhC5DBxjkwzUXwPy6fl/F2plNyn05ikX6xDa0bTPUJ9+qgg6ZZLAGewRmPJo12Op/PJDOnSLqKTKcVAidAHCxRJZlYyQeJrbg=
  - secure: AU8+V+5Oj2k7j5a5HnQN4pLpdvcomiiZCW5Z31+7lc6tnL/UNNdZVx8pjobQxyN8GxqgaT8HMH/ENPI4Sy7TCMJw3BDTaOXPtXChvxIyKUwQPnvB32R2UEF7dkM3olDZ1auZyQxizX6uz8xdwin2uXCBxnSNAysNFyZiINMj7P1OXEbCHHojaUNBj2/AyWvyUYiNs88vu5Als9Ut5jA06M5rxAvwoexqDPrR9Sq4MUuuqyt89fEbXVuuhHj2MEUQIarA40fS0ifUssS13A7c4J0K2ftKPsiRo7LpHKuT+d0GNHRYCjMwEYKSbBFCA2yAj9XnhtXNtz8kxRMqvBYHAdUxEeON9NNim+Ks7fMszUQL3bXi50pM3q7SgnCRNWzKpotaFLJmkxNu5NPUd6dIlcbgo5R6GJqIaXxpfhmSuEuHVAIwuy0LXckzuCSIWEFnB6lkYEZdMWxG76H7nMiw0H0yq1Mfy+o2FUkqbWDHpJkd8OVgxyJYyVrECvRbVK273ff51DLkoqjWFwH8ClR463miMl5S0GZ6ZD7q/w2A3JljhXpD47W7wARd94k7RqWUCr1kYwUzGOegGz7oyEQBdF0zc899eyedRHNxSUqDEO9Ds3SBxwrLdOmH52oXtPGaBUK53pzvmVDIdIJuofxgdls8hUxiGD+C3QVXywVov+w=
